### ISSUE TITLE
Need post URL scheme

### ISSUE THREAD

**Issue by imiller-gpfw** [vimeo/VIMDeeplink#4]
Love that you guys are allowing the ability to invoke the Vimeo app and load a video for viewing.  Any plans for including a URL scheme for posting video to the user's account?

**Comment by Dashron** [comment]
The Vimeo application adds a share extension, which should be available through the native share sheet. If a video is shared to this extension, it should automatically open the Vimeo app and start uploading to the logged-in users account.

Additionally, the [VIMNetworking](https://github.com/vimeo/VIMNetworking) library provides a robust system for handling uploads on your own, but this requires the user to log in to your app.

Do either of these work for you? Or do you have a third usecase? If so, I would love to hear more.

**Comment by alfiehanssen** [comment]
Also worth adding, if the user does not have the Vimeo iOS app installed and thus does not have the extension installed, the user can still use the OS integrated "post to Vimeo" extension. 

Fyi, our deeplinking taxonomy will expand significantly later this summer. It'll include deeplinking to upload related views. But deeplinking to initiate an upload raises issues related to the Vimeo App being able to access the video to be uploaded / sandboxing etc. Definitely something we'd like to explore.

**Comment by alfiehanssen** [comment]
@imiller-gpfw We do have a deeplink to open the Vimeo iOS app and navigate to the beginning of the upload flow. Otherwise, if you're talking about uploading a video file that resides in a different app's directory we can't do that at the moment. We could probably add support for passing a PHAsset identifier to the Vimeo iOS app and initiating an upload from there.
